# Generated by Django 2.2.4 on 2019-11-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerseOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], unique=True)),
                ('book', models.CharField(max_length=100)),
                ('chapter', models.CharField(max_length=100)),
                ('verse', models.CharField(max_length=100)),
                ('scripture', models.TextField()),
            ],
        ),
    ]
