# Generated by Django 2.2.4 on 2019-11-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verseoftheday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verseoftheday',
            name='day',
            field=models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (0, 'Sunday')], unique=True),
        ),
    ]
