# Generated by Django 2.2.4 on 2019-11-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verseoftheday', '0002_auto_20191113_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verseoftheday',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=12, unique=True),
        ),
    ]
