# Generated by Django 2.2.4 on 2019-11-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verseoftheday', '0003_auto_20191113_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verseoftheday',
            options={'ordering': ('day',), 'verbose_name_plural': 'verse of the day'},
        ),
    ]
