# Generated by Django 2.2.4 on 2019-11-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
    ]
