# Generated by Django 2.2.4 on 2019-11-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191114_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
