# Generated by Django 2.2.4 on 2019-11-13 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('year', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=150)),
                ('subject_code', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=10)),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_dashboard.YearLevel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('user', models.OneToOneField(limit_choices_to=models.Q(is_student=True), on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_studentprofile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lrn', models.CharField(max_length=20)),
                ('landline_number', models.CharField(blank=True, max_length=11, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=13, null=True)),
                ('address', models.TextField(blank=True, max_length=300)),
                ('mothers_name', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(max_length=50)),
                ('contact_person_name', models.CharField(max_length=50)),
                ('contact_person_number', models.CharField(max_length=12, verbose_name='Phone number of Contact Person')),
                ('class_advisor', models.ForeignKey(limit_choices_to=models.Q(is_teacher=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentprofile_class_advisor', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_dashboard.Section')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_dashboard.YearLevel')),
            ],
            options={
                'db_table': 'accounts_studentprofile',
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('user', models.OneToOneField(limit_choices_to=models.Q(is_student=True), on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('period', models.PositiveSmallIntegerField(choices=[(1, 'First Grading'), (2, 'Second Grading'), (3, 'Third Grading'), (4, 'Fourth Grading'), (5, 'First Semester'), (6, 'Second Semester')])),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student_dashboard.Subject')),
            ],
        ),
    ]
