# Generated by Django 2.2.4 on 2019-11-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=78.88, max_digits=4),
            preserve_default=False,
        ),
    ]
