# Generated by Django 2.2.4 on 2019-11-13 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0002_studentgrade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='user',
            field=models.OneToOneField(limit_choices_to=models.Q(is_student=True), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
