# Generated by Django 2.2.4 on 2019-11-13 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0003_auto_20191113_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='user',
            field=models.ForeignKey(limit_choices_to=models.Q(is_student=True), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
