# Generated by Django 2.2.4 on 2019-11-14 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0004_auto_20191113_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='year_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_dashboard.YearLevel'),
        ),
    ]
