# Generated by Django 2.2.4 on 2019-11-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0005_section_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='period',
            field=models.PositiveSmallIntegerField(choices=[('First Grading', 'First Grading'), ('Second Grading', 'Second Grading'), ('Third Grading', 'Third Grading'), ('Fourth Grading', 'Fourth Grading'), ('First Semester', 'First Semester'), ('Second Semester', 'Second Semester')]),
        ),
    ]
