# Generated by Django 2.2.4 on 2021-08-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0008_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_subjects',
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_subjects',
            field=models.ManyToManyField(to='student_dashboard.Subject'),
        ),
    ]
