# Generated by Django 2.2.4 on 2021-08-13 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0010_auto_20210813_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student_dashboard.Subject'),
        ),
    ]
