# Generated by Django 2.2.4 on 2021-08-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0011_auto_20210813_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
