# Generated by Django 2.2.4 on 2021-08-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0013_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_subject',
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_subject',
            field=models.ManyToManyField(to='student_dashboard.Subject'),
        ),
    ]
